
labels:
  org.opencontainers.image.title: "Event management"
  org.opencontainers.image.description: "Event management."
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"

args:
  TEMPIO_VERSION: "2023.11.10"
