# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.0"
slug: example
description: Example add-on
url: "https://github.com/MangkhaletSuad/addons-example.git"
webui: "http://[HOST]:[PORT:4449]"

parnel-icon: "mdi:cctv"
panel_title: Example
panel_admin: false

# add sidebar
ingress: true
ingress_entry: dashboard/

port:
  4449/tcp:4449

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
  - config:rw
  - ssl
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
