name: "Event Management"
version: "0.1.0"
slug: "Event Management"
description: "Event Management add-on"
url: "https://github.com/MangkhaletSuad/addons-example.git"
init: false

ingress: true
ingress_port: 80

panel_icon: "mdi:cctv"
panel_title: "Event Management"

arch:
  - "armhf"
  - "armv7"
  - "aarch64"
  - "amd64"
  - "i386"

options:
  message: "str?"

schema:
  message: "str?"
  image: "ghcr.io/home-assistant/{arch}-addon-example"
