name: "Example add-on"
version: "Test"
slug: "example"
description: "Example add-on"
url: "https://github.com/MangkhaletSuad/addons-example.git"
init: false

ingress: true
ingress_port: 8080

panel_icon: "mdi:cctv"
panel_title: "Example"
panel_admin: false

arch:
  - "armhf"
  - "armv7"
  - "aarch64"
  - "amd64"
  - "i386"

map:
  - "share:rw"
  - "config:rw"
  - "media:rw"
  - "ssl"

options:
  message: "Test"

schema:
  message: "str?"
  image: "ghcr.io/home-assistant/{arch}-addon-example"
