# # https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
# name: Example add-on
# version: "1.2.0"
# slug: example
# description: Example add-on
# url: "https://github.com/MangkhaletSuad/addons-example.git"
# webui: "http://[HOST]:[PORT:4444]"

# parnel-icon: "mdi:cctv"
# panel_title: Example
# panel_admin: false

# # add sidebar
# ingress: true
# ingress_entry: /
# ingress_port: 4444

# port:
#   5000/tcp: 4444

# arch:
#   - armhf
#   - armv7
#   - aarch64
#   - amd64
#   - i386
# init: false
# map:
#   - share:rw
#   - config:rw
#   - media:rw
#   - ssl
# options:
#   message: "Hello world..."
# schema:
#   message: "str?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
# services:
#   - "mqtt:want"


name: "Hello world"
description: "My first real add-on!"
version: "1.1.0"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  5000/tcp: 4444
