# # https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
# name: Example add-on
# version: "1.2.0"
# slug: example
# description: Example add-on
# url: "https://github.com/MangkhaletSuad/addons-example.git"
# webui: "http://[HOST]:[PORT:8080]"

# parnel-icon: "mdi:cctv"
# panel_title: Example
# panel_admin: false

# # add sidebar
# ingress: true
# ingress_entry: /
# ingress_port: 8080

# port:
#   8080/tcp: 8080

# arch:
#   - armhf
#   - armv7
#   - aarch64
#   - amd64
#   - i386
# init: false
# map:
#   - share:rw
#   - config:rw
#   - media:rw
#   - ssl
# options:
#   message: "Test_Test"
# schema:
#   message: "str?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
# services:
#   - "mqtt:want"

---
name: Grafanas
version: dev
slug: grafana
description: The open platform for beautiful analytics and monitoring
url: https://github.com/hassio-addons/addon-grafana
codenotary: codenotary@frenck.dev
startup: services
ingress: true
ingress_port: 1337
ingress_stream: true
init: false
panel_icon: mdi:chart-timeline
panel_title: Grafana
arch:
  - aarch64
  - amd64
  - armv7
map:
  - config
  - ssl
options:
  plugins: []
  custom_plugins: []
  env_vars: []
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
ports:
  8080/tcp: null
ports_description:
  8080/tcp: Not required for Ingress
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  plugins:
    - str
  custom_plugins:
    - name: str
      url: str
      unsigned: bool?
  certfile: str
  keyfile: str
  ssl: bool
  grafana_ingress_user: str?
  env_vars:
    - name: match(^GF_([A-Z0-9_])+$)
      value: str
