name: "Event management"
version: "0.1.0"
slug: "Event"
description: "Event management add-on"
url: "https://github.com/MangkhaletSuad/addons-example.git"
init: false

ingress: true
ingress_port: 8202

panel_icon: "mdi:cctv"
panel_title: "Example"

arch:
  - "armhf"
  - "armv7"
  - "aarch64"
  - "amd64"
  - "i386"

options:

schema:
  message: "str?"

